// Seed script to add sample Honolulu listings

import { PrismaClient } from '@prisma/client';
import { PrismaLibSql } from '@prisma/adapter-libsql';

const adapter = new PrismaLibSql({
    url: `file:${process.cwd()}/prisma/dev.db`,
});

const prisma = new PrismaClient({ adapter });

const sampleListings = [
    {
        source: 'manual',
        sourceId: 'sample-1',
        url: 'https://honolulu.craigslist.org/search/apa?query=waikiki#search=1~gallery~0~0',
        title: 'Stunning Ocean View 1BR in Waikiki - Fully Renovated',
        description: 'Beautiful 1 bedroom with panoramic ocean views. Central AC, in-unit washer/dryer, covered parking included. Building has pool and BBQ area. Private lanai to enjoy the sunset.',
        addressRaw: '2500 Kalakaua Ave, Honolulu, HI',
        buildingName: 'Pacific Beach Hotel Residences',
        lat: 21.2769,
        lng: -157.8268,
        neighborhoodLabel: 'Waikiki',
        rentBase: 3200,
        feesParsed: JSON.stringify({ parking: 0, utilities: null, other: null, parkingIncluded: true, utilitiesIncluded: [], uncertainties: [] }),
        rentAllInEstimate: 3200,
        beds: 1,
        baths: 1,
        sqft: 680,
        parking: 'yes',
        parkingType: 'covered',
        ac: 'yes',
        acType: 'central',
        wdInUnit: 'yes',
        lanai: 'yes',
        outdoorSpace: 'private',
        amenities: JSON.stringify(['pool', 'bbq']),
        viewTags: JSON.stringify(['ocean']),
        photos: JSON.stringify([]),
        status: 'new',
        redFlags: JSON.stringify([]),
        scoreTotal: 68,
        scoreBreakdown: JSON.stringify({
            view: 20,
            viewDetails: [{ tag: 'ocean', points: 20, uncertain: false }],
            lanai: 20,
            outdoor: 15,
            amenities: 14,
            amenityDetails: [{ name: 'pool', points: 8 }, { name: 'bbq', points: 6 }],
            bonus: 0,
            penalties: 0,
            penaltyDetails: [],
            total: 69,
        }),
        dedupeKey: '2500 kalakaua ave honolulu hi|pacific beach hotel residences|1br|1ba|700sqft',
    },
    {
        source: 'manual',
        sourceId: 'sample-2',
        url: 'https://honolulu.craigslist.org/search/apa?query=ward+village#search=1~gallery~0~0',
        title: 'Modern 1BR at Ward Village - Pool & Gym',
        description: 'Sleek modern unit in brand new high-rise. Split AC, washer/dryer in-unit, 1 parking stall included. Amazing city and mountain views from your private lanai. Building features pool, gym, and pickleball courts!',
        addressRaw: '1388 Ala Moana Blvd, Honolulu, HI',
        buildingName: 'Ae\'o Condos',
        lat: 21.2921,
        lng: -157.8544,
        neighborhoodLabel: 'Ala Moana',
        rentBase: 3100,
        feesParsed: JSON.stringify({ parking: 0, utilities: null, other: null, parkingIncluded: true, utilitiesIncluded: [], uncertainties: ['Utility costs unknown'] }),
        rentAllInEstimate: 3100,
        beds: 1,
        baths: 1,
        sqft: 620,
        parking: 'yes',
        parkingType: 'garage',
        ac: 'yes',
        acType: 'split',
        wdInUnit: 'yes',
        lanai: 'yes',
        outdoorSpace: 'private',
        amenities: JSON.stringify(['pool', 'gym', 'pickleball']),
        viewTags: JSON.stringify(['city', 'mountain']),
        photos: JSON.stringify([]),
        status: 'new',
        redFlags: JSON.stringify([]),
        scoreTotal: 75,
        scoreBreakdown: JSON.stringify({
            view: 11,
            viewDetails: [{ tag: 'mountain', points: 10, uncertain: false }, { tag: 'city', points: 2, uncertain: false }],
            lanai: 20,
            outdoor: 15,
            amenities: 22,
            amenityDetails: [{ name: 'pool', points: 8 }, { name: 'pickleball', points: 10 }, { name: 'gym', points: 4 }],
            bonus: 5,
            penalties: 0,
            penaltyDetails: [],
            total: 73,
        }),
        dedupeKey: '1388 ala moana blvd honolulu hi|aeo condos|1br|1ba|600sqft',
    },
    {
        source: 'manual',
        sourceId: 'sample-3',
        url: 'https://honolulu.craigslist.org/search/apa?query=kapiolani+park#search=1~gallery~0~0',
        title: 'Diamond Head Views - Quiet 1BR with Lanai',
        description: 'Peaceful location near Kapiolani Park. Gorgeous Diamond Head and ocean views. Central AC, washer/dryer included, covered parking. Small lanai perfect for morning coffee.',
        addressRaw: '2979 Kalakaua Ave, Honolulu, HI',
        buildingName: 'Diamond Head Ambassador',
        lat: 21.2632,
        lng: -157.8142,
        neighborhoodLabel: 'Diamond Head',
        rentBase: 2850,
        feesParsed: JSON.stringify({ parking: 0, utilities: null, other: null, parkingIncluded: true, utilitiesIncluded: [], uncertainties: [] }),
        rentAllInEstimate: 2850,
        beds: 1,
        baths: 1,
        sqft: 590,
        parking: 'yes',
        parkingType: 'covered',
        ac: 'yes',
        acType: 'central',
        wdInUnit: 'yes',
        lanai: 'yes',
        outdoorSpace: 'private',
        amenities: JSON.stringify(['pool']),
        viewTags: JSON.stringify(['diamond_head', 'ocean']),
        photos: JSON.stringify([]),
        status: 'shortlisted',
        redFlags: JSON.stringify([]),
        scoreTotal: 78,
        scoreBreakdown: JSON.stringify({
            view: 21,
            viewDetails: [{ tag: 'ocean', points: 20, uncertain: false }, { tag: 'diamond_head', points: 4, uncertain: false }],
            lanai: 20,
            outdoor: 15,
            amenities: 8,
            amenityDetails: [{ name: 'pool', points: 8 }],
            bonus: 0,
            penalties: 0,
            penaltyDetails: [],
            total: 64,
        }),
        dedupeKey: '2979 kalakaua ave honolulu hi|diamond head ambassador|1br|1ba|600sqft',
    },
    {
        source: 'craigslist',
        sourceId: 'sample-4',
        url: 'https://honolulu.craigslist.org/search/apa?query=waikiki+beach#search=1~gallery~0~0',
        title: 'Affordable 1BR Waikiki - Walk to Beach',
        description: 'Great location just 2 blocks from the beach. Window AC, in-unit washer/dryer, street parking available for extra $100/month. No lanai but building has rooftop deck with BBQ.',
        addressRaw: '245 Lewers St, Honolulu, HI',
        buildingName: 'Lewers Tower',
        lat: 21.2791,
        lng: -157.8302,
        neighborhoodLabel: 'Waikiki',
        rentBase: 2700,
        feesParsed: JSON.stringify({ parking: 100, utilities: null, other: null, parkingIncluded: false, utilitiesIncluded: [], uncertainties: [] }),
        rentAllInEstimate: 2800,
        beds: 1,
        baths: 1,
        sqft: 520,
        parking: 'yes',
        parkingType: 'street',
        ac: 'yes',
        acType: 'window',
        wdInUnit: 'yes',
        lanai: 'no',
        outdoorSpace: 'shared',
        amenities: JSON.stringify(['bbq']),
        viewTags: JSON.stringify(['city']),
        photos: JSON.stringify([]),
        status: 'new',
        redFlags: JSON.stringify([]),
        scoreTotal: 22,
        scoreBreakdown: JSON.stringify({
            view: 8,
            viewDetails: [{ tag: 'city', points: 8, uncertain: false }],
            lanai: 0,
            outdoor: 8,
            amenities: 6,
            amenityDetails: [{ name: 'bbq', points: 6 }],
            bonus: 0,
            penalties: 0,
            penaltyDetails: [],
            total: 22,
        }),
        dedupeKey: '245 lewers st honolulu hi|lewers tower|1br|1ba|500sqft',
    },
    {
        source: 'manual',
        sourceId: 'sample-5',
        url: 'https://honolulu.craigslist.org/search/apa?query=kakaako+luxury#search=1~gallery~0~0',
        title: 'Luxury 1BR in Kakaako - Ocean & Marina Views',
        description: 'High-floor unit with stunning marina and ocean views. Split AC system, in-unit W/D, 1 covered parking. Building amenities include infinity pool, BBQ pavilion, and fitness center. Private lanai.',
        addressRaw: '555 South St, Honolulu, HI',
        buildingName: 'Waiea Tower',
        lat: 21.2941,
        lng: -157.8601,
        neighborhoodLabel: 'Ala Moana',
        rentBase: 3400,
        feesParsed: JSON.stringify({ parking: 0, utilities: null, other: null, parkingIncluded: true, utilitiesIncluded: ['water'], uncertainties: [] }),
        rentAllInEstimate: 3400,
        beds: 1,
        baths: 1,
        sqft: 720,
        parking: 'yes',
        parkingType: 'covered',
        ac: 'yes',
        acType: 'split',
        wdInUnit: 'yes',
        lanai: 'yes',
        outdoorSpace: 'private',
        amenities: JSON.stringify(['pool', 'bbq', 'gym']),
        viewTags: JSON.stringify(['ocean', 'marina']),
        photos: JSON.stringify([]),
        status: 'contacted',
        redFlags: JSON.stringify([]),
        scoreTotal: 82,
        scoreBreakdown: JSON.stringify({
            view: 22,
            viewDetails: [{ tag: 'ocean', points: 20, uncertain: false }, { tag: 'marina', points: 2, uncertain: false }],
            lanai: 20,
            outdoor: 15,
            amenities: 18,
            amenityDetails: [{ name: 'pool', points: 8 }, { name: 'bbq', points: 6 }, { name: 'gym', points: 4 }],
            bonus: 5,
            penalties: 0,
            penaltyDetails: [],
            total: 80,
        }),
        dedupeKey: '555 south st honolulu hi|waiea tower|1br|1ba|700sqft',
    },
];


async function seed() {
    console.log('🌱 Seeding database with sample Honolulu listings...');

    for (const listing of sampleListings) {
        await prisma.listing.create({
            data: listing,
        });
        console.log(`  ✓ Added: ${listing.title}`);
    }

    console.log(`\n✅ Seeded ${sampleListings.length} listings!`);
    await prisma.$disconnect();
}

seed().catch((e) => {
    console.error(e);
    process.exit(1);
});
